### ISSUE TITLE
why  .h5?

### ISSUE THREAD

**Issue by seuxiaoge** [HiLab-git/SSL4MIS#6]
hello, why is the data in .h5 format?How do I visualize it?

**Comment by Luoxd1996** [comment]
Hi, seuxiaoge;
just because my personal habit, which saved the processed data as .h5 file. You can read it as NumPy array and plot it by matplotlib or save it as NIfTI data and show it by ITK SNAP.
Best wishes;
xdluo.

**Comment by seuxiaoge** [comment]
Traceback (most recent call last):
  File "E:/code/SSL4MIS-master/code/train_unet_2D_adversarial_network.py", line 283, in <module>
    train(args, snapshot_path)
  File "E:/code/SSL4MIS-master/code/train_unet_2D_adversarial_network.py", line 138, in train
    for i_batch, sampled_batch in enumerate(trainloader):
  File "D:\Anaconda3\envs\semi\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda3\envs\semi\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\Anaconda3\envs\semi\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\semi\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\semi\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\semi\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\semi\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'train.<locals>.worker_init_fn'

**Comment by seuxiaoge** [comment]
what‘s this？

**Comment by Luoxd1996** [comment]
I don't know, please make sure your relevant-requirements are right firstly. And then, debug your code carefully. By the way, this repo has been tested many times on Ubuntu20.04, there aren't  any bug.

**Comment by buloseshi** [comment]
> hello, why is the data in .h5 format?How do I visualize it?
Hi, do you know how to convert a normal data set to h5 format？
